/**
 *
 *  Manga.h
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#pragma once
#include <drogon/orm/Result.h>
#include <drogon/orm/Row.h>
#include <drogon/orm/Field.h>
#include <drogon/orm/SqlBinder.h>
#include <drogon/orm/Mapper.h>
#include <trantor/utils/Date.h>
#include <trantor/utils/Logger.h>
#include <json/json.h>
#include <string>
#include <memory>
#include <vector>
#include <tuple>
#include <stdint.h>
#include <iostream>

using namespace drogon::orm;
namespace drogon
{
namespace orm
{
class DbClient;
using DbClientPtr = std::shared_ptr<DbClient>;
}
}
namespace drogon_model
{
namespace sqlite3 
{
class Title;
class Chapter;
class Tag;
class MangaTag;
class Person;
class Author;
class Person;
class Artist;

class Manga
{
  public:
    struct Cols
    {
        static const std::string _id;
        static const std::string _type;
        static const std::string _country_of_origin;
        static const std::string _publication_status;
        static const std::string _scanlation_status;
        static const std::string _mal_id;
        static const std::string _anilist_id;
        static const std::string _mangaupdates_id;
    };

    const static int primaryKeyNumber;
    const static std::string tableName;
    const static bool hasPrimaryKey;
    const static std::string primaryKeyName;
    using PrimaryKeyType = uint64_t;
    const PrimaryKeyType &getPrimaryKey() const;

    /**
     * @brief constructor
     * @param r One row of records in the SQL query result.
     * @param indexOffset Set the offset to -1 to access all columns by column names, 
     * otherwise access all columns by offsets.
     * @note If the SQL is not a style of 'select * from table_name ...' (select all 
     * columns by an asterisk), please set the offset to -1.
     */
    explicit Manga(const Row &r, const ssize_t indexOffset = 0) noexcept;

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     */
    explicit Manga(const Json::Value &pJson) noexcept(false);

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     * @param pMasqueradingVector The aliases of table columns.
     */
    Manga(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false);

    Manga() = default;
    
    void updateByJson(const Json::Value &pJson) noexcept(false);
    void updateByMasqueradedJson(const Json::Value &pJson,
                                 const std::vector<std::string> &pMasqueradingVector) noexcept(false);
    static bool validateJsonForCreation(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForCreation(const Json::Value &,
                                                const std::vector<std::string> &pMasqueradingVector,
                                                    std::string &err);
    static bool validateJsonForUpdate(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForUpdate(const Json::Value &,
                                          const std::vector<std::string> &pMasqueradingVector,
                                          std::string &err);
    static bool validJsonOfField(size_t index,
                          const std::string &fieldName,
                          const Json::Value &pJson, 
                          std::string &err, 
                          bool isForCreation);

    /**  For column id  */
    ///Get the value of the column id, returns the default value if the column is null
    const uint64_t &getValueOfId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<uint64_t> &getId() const noexcept;

    ///Set the value of the column id
    void setId(const uint64_t &pId) noexcept;


    /**  For column type  */
    ///Get the value of the column type, returns the default value if the column is null
    const uint64_t &getValueOfType() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<uint64_t> &getType() const noexcept;

    ///Set the value of the column type
    void setType(const uint64_t &pType) noexcept;


    /**  For column country_of_origin  */
    ///Get the value of the column country_of_origin, returns the default value if the column is null
    const std::string &getValueOfCountryOfOrigin() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getCountryOfOrigin() const noexcept;

    ///Set the value of the column country_of_origin
    void setCountryOfOrigin(const std::string &pCountryOfOrigin) noexcept;
    void setCountryOfOrigin(std::string &&pCountryOfOrigin) noexcept;


    /**  For column publication_status  */
    ///Get the value of the column publication_status, returns the default value if the column is null
    const uint64_t &getValueOfPublicationStatus() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<uint64_t> &getPublicationStatus() const noexcept;

    ///Set the value of the column publication_status
    void setPublicationStatus(const uint64_t &pPublicationStatus) noexcept;


    /**  For column scanlation_status  */
    ///Get the value of the column scanlation_status, returns the default value if the column is null
    const bool &getValueOfScanlationStatus() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<bool> &getScanlationStatus() const noexcept;

    ///Set the value of the column scanlation_status
    void setScanlationStatus(const bool &pScanlationStatus) noexcept;


    /**  For column mal_id  */
    ///Get the value of the column mal_id, returns the default value if the column is null
    const uint64_t &getValueOfMalId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<uint64_t> &getMalId() const noexcept;

    ///Set the value of the column mal_id
    void setMalId(const uint64_t &pMalId) noexcept;
    void setMalIdToNull() noexcept;


    /**  For column anilist_id  */
    ///Get the value of the column anilist_id, returns the default value if the column is null
    const uint64_t &getValueOfAnilistId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<uint64_t> &getAnilistId() const noexcept;

    ///Set the value of the column anilist_id
    void setAnilistId(const uint64_t &pAnilistId) noexcept;
    void setAnilistIdToNull() noexcept;


    /**  For column mangaupdates_id  */
    ///Get the value of the column mangaupdates_id, returns the default value if the column is null
    const uint64_t &getValueOfMangaupdatesId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<uint64_t> &getMangaupdatesId() const noexcept;

    ///Set the value of the column mangaupdates_id
    void setMangaupdatesId(const uint64_t &pMangaupdatesId) noexcept;
    void setMangaupdatesIdToNull() noexcept;



    static size_t getColumnNumber() noexcept {  return 8;  }
    static const std::string &getColumnName(size_t index) noexcept(false);

    Json::Value toJson() const;
    Json::Value toMasqueradedJson(const std::vector<std::string> &pMasqueradingVector) const;
    /// Relationship interfaces
    void getTitle(const DbClientPtr &clientPtr, 
                  const std::function<void(std::vector<Title>)> &rcb,
                  const ExceptionCallback &ecb) const;
    void getChapter(const DbClientPtr &clientPtr, 
                    const std::function<void(std::vector<Chapter>)> &rcb,
                    const ExceptionCallback &ecb) const;
    void getTag(const DbClientPtr &clientPtr, 
                const std::function<void(std::vector<std::pair<Tag,MangaTag>>)> &rcb,
                const ExceptionCallback &ecb) const;
    void getPerson(const DbClientPtr &clientPtr, 
                   const std::function<void(std::vector<std::pair<Person,Author>>)> &rcb,
                   const ExceptionCallback &ecb) const;
    void getPerson(const DbClientPtr &clientPtr, 
                   const std::function<void(std::vector<std::pair<Person,Artist>>)> &rcb,
                   const ExceptionCallback &ecb) const;
  private:
    friend Mapper<Manga>;
    static const std::vector<std::string> &insertColumns() noexcept;
    void outputArgs(drogon::orm::internal::SqlBinder &binder) const;
    const std::vector<std::string> updateColumns() const;
    void updateArgs(drogon::orm::internal::SqlBinder &binder) const;
    ///For mysql or sqlite3
    void updateId(const uint64_t id);
    std::shared_ptr<uint64_t> id_;
    std::shared_ptr<uint64_t> type_;
    std::shared_ptr<std::string> countryOfOrigin_;
    std::shared_ptr<uint64_t> publicationStatus_;
    std::shared_ptr<bool> scanlationStatus_;
    std::shared_ptr<uint64_t> malId_;
    std::shared_ptr<uint64_t> anilistId_;
    std::shared_ptr<uint64_t> mangaupdatesId_;
    struct MetaData
    {
        const std::string colName_;
        const std::string colType_;
        const std::string colDatabaseType_;
        const ssize_t colLength_;
        const bool isAutoVal_;
        const bool isPrimaryKey_;
        const bool notNull_;
    };
    static const std::vector<MetaData> metaData_;
    bool dirtyFlag_[8]={ false };
  public:
    static const std::string &sqlForFindingByPrimaryKey()
    {
        static const std::string sql="select * from " + tableName + " where id = ?";
        return sql;                   
    }

    static const std::string &sqlForDeletingByPrimaryKey()
    {
        static const std::string sql="delete from " + tableName + " where id = ?";
        return sql;                   
    }
    std::string sqlForInserting(bool &needSelection) const
    {
        std::string sql="insert into " + tableName + " (";
        size_t parametersCount = 0;
        needSelection = false;
        if(dirtyFlag_[1])
        {
            sql += "type,";
            ++parametersCount;
        }
        if(dirtyFlag_[2])
        {
            sql += "country_of_origin,";
            ++parametersCount;
        }
        if(dirtyFlag_[3])
        {
            sql += "publication_status,";
            ++parametersCount;
        }
        if(dirtyFlag_[4])
        {
            sql += "scanlation_status,";
            ++parametersCount;
        }
        if(dirtyFlag_[5])
        {
            sql += "mal_id,";
            ++parametersCount;
        }
        if(dirtyFlag_[6])
        {
            sql += "anilist_id,";
            ++parametersCount;
        }
        if(dirtyFlag_[7])
        {
            sql += "mangaupdates_id,";
            ++parametersCount;
        }
        if(parametersCount > 0)
        {
            sql[sql.length()-1]=')';
            sql += " values (";
        }
        else
            sql += ") values (";
        
        if(dirtyFlag_[1])
        {
            sql.append("?,");

        } 
        if(dirtyFlag_[2])
        {
            sql.append("?,");

        } 
        if(dirtyFlag_[3])
        {
            sql.append("?,");

        } 
        if(dirtyFlag_[4])
        {
            sql.append("?,");

        } 
        if(dirtyFlag_[5])
        {
            sql.append("?,");

        } 
        if(dirtyFlag_[6])
        {
            sql.append("?,");

        } 
        if(dirtyFlag_[7])
        {
            sql.append("?,");

        } 
        if(parametersCount > 0)
        {
            sql.resize(sql.length() - 1);
        }
        sql.append(1, ')');
        LOG_TRACE << sql;
        return sql;   
    }
};
} // namespace sqlite3
} // namespace drogon_model
